### ISSUE TITLE
ERROR ~ Validation of pipeline parameters failed! (fastq/bam)

### ISSUE THREAD

**Issue by LucyNanopore** [epi2me-labs/wf-metagenomics#112]
### Ask away!

I am trying to run the following nanopore sequencing pipeline:
nextflow run epi2me-labs/wf-metagenomics \
--fastq $fastq_path \
-profile singularity  \
--kraken2_memory_mapping \
--database_set PlusPF-8 \
--amr \
--amr_db resfinder \
--out_dir $output
However, I get the following error message:
ERROR ~ Validation of pipeline parameters failed!

 -- Check '.nextflow.log' file for details
ERROR ~ * Bad parameter configuration. You must select only one option of:
    --fastq
    --bam

 -- Check '.nextflow.log' file for details
/opt/sge/default/spool/gpu-49/job_scripts/1783636: line 44: --fastq: command not found
/opt/sge/default/spool/gpu-49/job_scripts/1783636: line 46: -profile: command not found
/opt/sge/default/spool/gpu-49/job_scripts/1783636: line 49: --kraken2_memory_mapping: command not found
/opt/sge/default/spool/gpu-49/job_scripts/1783636: line 50: --database_set: command not found
/opt/sge/default/spool/gpu-49/job_scripts/1783636: line 53: --amr: command not found
/opt/sge/default/spool/gpu-49/job_scripts/1783636: line 54: --amr_db: command not found
/opt/sge/default/spool/gpu-49/job_scripts/1783636: line 56: --out_dir: command not found

I have my barcodes in a separate folder, all of them only contain the fastq.gz files, and have been puzzled as the config file I am using has no mention of bam.

**Comment by nggvs** [comment]
Hi @LucyNanopore ,
would you mind to open this as bug completing the formular? It asks for some info that may be helpful for solving the problem :)
Thank you very much in advance!

**Comment by nggvs** [comment]
No problem at all! When you click on new issue, you can choose between 3 models:
![image](https://github.com/epi2me-labs/wf-metagenomics/assets/122800769/e8b70e98-d3c4-48a7-949b-0caa86636261)

Bug is for problems (it asks you for example the version of the workflow or the parameters you're using so that is more helpful to reproduce the errors), Questions are more appropriate if you want to ask something not in the docs and feature request is for feedback or things that you'd like to have in the workflow :)

**Comment by LucyNanopore** [comment]
Thank you, I have opened one now :)
