### ISSUE TITLE
Pinging home

### ISSUE THREAD

**Issue by Midnighter** [epi2me-labs/wf-metagenomics#14]
### What happened?

Not a bug report but just a note that it was a bit of an unpleasant surprise to find out that this workflow sends home data by default. I feel like that should be mentioned in the readme, as well as the `disable_ping` parameter.

### Operating System

Windows 10

### Workflow Execution

Command line

### Workflow Version

master

### Relevant log output

```shell
-
```

**Comment by cjw85** [comment]
This is correct, we have yet to add a link to the Oxford Nanopore Technologies Privacy Policy and Terms of use to our GitHub READMEs. Links to these can be found at the bottom of our blog site: https://labs.epi2me.io/.

The pings are similar to those sent by other ONT products (including MinKNOW and the Guppy basecaller) and are used to, for example, track usage of our workflows in order to better focus development resource. We do not send details concerning a user's data processed by the workflow.

Please contact support@nanoporetech.com if you have additional concerns.

**Comment by Midnighter** [comment]
I agree, it's a reasonable thing to do. Just that it shouldn't be surprising in my opinion. So I'm happy to know that you plan to add this information.
