### ISSUE TITLE
[Bug]: The README doesn't state how the database has been built

### ISSUE THREAD

**Issue by thecorz** [epi2me-labs/wf-metagenomics#34]
### What happened?

Species assignment can be very different depending on the database used. And as they said, "the species assignment is only as good as the database you use to match against". 

There's no info much info about how the database was created or where the reference sequences were taken from. Looking at the code I can see that the database is being downloaded from ONT cloud servers, the name mentions "targeted loci" so I assume it's been built with some of the parts of the NCBI's Targeted Loci project. But it's not mentioned anywhere which parts.

Could you make that info available?

Thanks 

### Operating System

ubuntu 20.04

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

2.0.8

### Relevant log output

```shell
No logs
```

**Comment by sarahjeeeze** [comment]
Hi, The kraken databases have been made by running kraken2 build with the FTP datasets from https://www.ncbi.nlm.nih.gov/refseq/targetedloci/. I will update the documentation to mention this.

**Comment by kagningemma** [comment]
The `nextflow run wf-metagenomics --help` command provides the following information about the database settings : 

>  --database_set         [string]  Sets the reference, databases and taxonomy datasets that will be used for classifying reads. Choices:   ['ncbi_16s_18s','ncbi_16s_18s_28s_ITS','PlusPF-8']. Workflow will require memory available to be slightly higher than the size of the database. PlusPF-8 database requires more than 8Gb. [default: ncbi_16s_18s] 

I would like minimap2 in the **epi2me-labs/wf-metagenomics** workflow to align sequences against a [custom database](https://rvdb.dbi.udel.edu/download/C-RVDBvCurrent.fasta.gz), which I downloaded an supplied to the `nextflow run epi2me-labs/wf-metagenomics` command. 
The command `nextflow run epi2me-labs/wf-metagenomics --fastq /Users/emmanuelkt/Downloads/E54_01to1_fasta_data/rep1_all.fastq.gz --classifier minimap2 –-database_set /Users/emmanuelkt/Downloads/C-RVDBvCurrent.fasta --out_dir /Users/emmanuelkt/Downloads/E54_01to1_fasta_data/output2_rep1` was successfully executed. However, the ncbi_16s_18s database was used instead of the supplied database. Is it possible to use a database different from  'ncbi_16s_18s','ncbi_16s_18s_28s_ITS' and 'PlusPF-8' ? If so, how ?

**Comment by nggvs** [comment]
Hi, 
Thank you for using the workflow! If you want to use your custom reference with the minimap2 pipeline, you need to use the flag `--reference`. You can take a look on this post to see an example: https://labs.epi2me.io/metagenomic-databases/

Please let us know if you have more questions about it
