### ISSUE TITLE
Extract automatically CSV of abundances

### ISSUE THREAD

**Issue by msubirana** [epi2me-labs/wf-metagenomics#68]
### Is your feature related to a problem?

Is it possible extract or convert the raw input to some abundance data similarly to the one that exports the "Export CSV" tag in the html generated by the pipe? Thanks

### Describe the solution you'd like

I'd like a file with all the relative abundances

### Describe alternatives you've considered

None

**Comment by nggvs** [comment]
Hi @msubirana,
Thank you for using the workflow and for your suggestion!
What do you refer exactly by raw input? Do you mean having an output table like the one that can be exported by using percentages instead of raw abundances?

**Comment by msubirana** [comment]
The wk generates the raw data from bracken and kracken but from the wf-metagenomics-report.html, is possible to generate a csv with the abundances of species, genus... (using the Export CSV botton). I'd like to generate the same output or similar without using the Export CSV, by using terminal or some Rscript to automatize the process. Or how can convert Bracken output file to the CSV exported by the html.

**Comment by nggvs** [comment]
Glad for your question then!

This's a new feature that is being released today (v2.6.0) [I let you know when this happens]. You will find a "abundance_table_rank.tsv" in the output directory for the last analysed rank, without the need to use the export button.

The only difference with the one in the report is that instead of having each taxonomic rank as a different column, it contains the full taxonomy string splitted by ';'.

**Comment by nggvs** [comment]
Hi @msubirana ,

Release v2.6.0 is ready and it should contain the feature you have requested. Please, if that is the case, close the issue and feel free to open a new one if you need it.
Thank you very much!

**Comment by msubirana** [comment]
Thanks for the quick response and thanks for this increible package!
